language: python

cache: pip

addons:
  apt:
    packages:
      - libfuzzy-dev

python:
    - "3.6-dev"
    - "3.7-dev"
    - "3.8-dev"

install:
    - pip install poetry
    - poetry install
    - git submodule init
    - git submodule update

script:
    - poetry run nosetests --with-coverage --cover-package=mail2misp tests/tests.py

after_success:
    - poetry run codecov
    - poetry run coveralls
