language: python

cache: pip

sudo: required

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages:
      - libstdc++6
      - libfuzzy-dev

python:
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"

install:
    - git clone git://github.com/stricaud/faup.git
    - pushd faup/build
    - cmake .. && make
    - sudo make install
    - popd
    - sudo ldconfig
    - pip install pipenv
    - pipenv install -d
    - git submodule init
    - git submodule update

script:
    - pipenv run nosetests --with-coverage --cover-package=mail2misp tests/tests.py

after_success:
    - pipenv run codecov
    - pipenv run coveralls
